<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            [
            'name'=>'anggur-plain',
            'price'=>'1000',
            'unit' => 1,
            'stock' => 10,
            'image'=>'/public/image/buah/anggur-plain.jpg',
            'categories_id'=>1,
            ],
            [
                'name'=>'anggur',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/anggur.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'apel-fuji-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/apel-fuji-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'apel-fuji',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/apel-fuji.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'apel',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/apel.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'apel-washington-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/apel-washington-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'apel-washington',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/apel-washington.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'apels-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/apels-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'apels',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/apels.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'bengkuang-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/bengkuang-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'bengkuang',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/bengkuang.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'jambu-kristal-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/jambu-kristal-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'jambu-kristal',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/jambu-kristal.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'jeruk-dua-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/jeruk-dua-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'jeruk-dua',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/jeruk-dua.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'jeruk-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/jeruk-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'jeruk',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/jeruk.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'mangggu-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/mangggu-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'mangggu',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/mangggu.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'melon-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/melon-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'melon',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/melon.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'nanas-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/nanas-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'nanas',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/nanas.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'pisang-dua-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/pisang-dua-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'pisang-dua',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/pisang-dua.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'pisang-satu-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/pisang-satu-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'pisang-satu',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/pisang-satu.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'pisang-tanduk-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/pisang-tanduk-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'pisang-tanduk',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/pisang-tanduk.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'salak-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/salak-plain.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'salak',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/salak.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'stroberi-13',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/stroberi-13.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'stroberi-14',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/stroberi-14.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'stroberi-16',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/stroberi-16.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'stroberi-18',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/stroberi-18.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'stroberi-19',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/buah/stroberi-19.jpg',
                'categories_id'=>1,
            ],
            [
                'name'=>'bawang-bombay-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/bawang-bombay-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'bawang-bombay',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/bawang-bombay.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'bawang-daun-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/bawang-daun-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'bawang-daun',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/bawang-daun.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'bawang-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/bawang-merah-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'bawang-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/bawang-merah.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'brokoli-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/brokoli-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'brokoli',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/brokoli.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'brokoli-putih-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/brokoli-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'brokoli-putih',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/brokoli-putih.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-gendot-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-gendot-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-gendot',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-gendot.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-hijau-besar-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-hijau-besar-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-hijau-besar',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-hijau-besar.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-keriting-hijau-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-keriting-hijau-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-keriting-hijau',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-keriting-hijau.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-merah-keriting-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-merah-keriting-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-keriting-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-keriting-merah.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-merah-besar-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-merah-besar-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-merah-besar',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-merah-besar.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-rawit-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-rawit-merah-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-rawit-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-rawit-merah.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-rawit-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-rawit-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'cabe-rawit',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/cabe-rawit.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'daun-jeruk-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/daun-jeruk-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'daun-jeruk',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/daun-jeruk.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'jagung-manis-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/jagung-manis-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'jagung-manis',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/jagung-manis.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'jamur-kuping-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/jamur-kuping-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'jamur-kuping',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/jamur-kuping.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'jengkol-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/jengkol-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'jengkol',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/jengkol.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'jeruk-purut-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/jeruk-purut-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'jeruk-purut',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/jeruk-purut.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'kale-dua-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/kale-dua-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'kale-dua',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/kale-dua.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'kale-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/kale-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'kale',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/kale.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'kentang-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/kentang-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'kentang',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/kentang.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'lengkuas-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/lengkuas-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'lengkuas',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/lengkuas.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'leunca-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/leunca-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'leunca',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/leunca.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'mentimun-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/mentimun-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'mentimun',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/mentimun.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'pakcoy-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/pakcoy-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'pakcoy',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/pakcoy.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'paprika-hijau-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/paprika-hijau-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'paprika-hijau',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/paprika-hijau.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'paprika-kuning-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/paprika-kuning-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'paprika-kuning',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/paprika-kuning.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'paprika-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/paprika-merah-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'paprika-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/paprika-merah.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'pare-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/pare-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'pare',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/pare.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'sawi-hijau-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/sawi-hijau-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'sawi-hijau',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/sawi-hijau.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'sawi-putih-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/sawi-putih-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'sawi-putih',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/sawi-putih.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'seledri-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/seledri-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'seledri',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/seledri.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'terong-hijau-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/terong-hijau-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'terong-hijau',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/terong-hijau.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'terong-ungu-besar-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/terong-ungu-besar-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'terong-ungu-besar',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/terong-ungu-besar.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'toge-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/toge-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'toge',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/toge.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'tomat-ceri-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/tomat-ceri-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'tomat-ceri',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/tomat-ceri.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'ubi-cilembu-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/ubi-cilembu-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'ubi-cilembu',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/ubi-cilembu.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'wortel-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/wortel-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'wortel',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/wortel.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'zuchini-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/zuchini-plain.jpg',
                'categories_id'=>2,
            ],
            [
                'name'=>'zuchini',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/sayur/zuchini.jpg',
                'categories_id'=>2,
            ],
            
            [
                'name'=>'asin-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/asin-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'asin',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/asin.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'ayam-pejantan-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/ayam-pejantan-palin.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'ayam-pejantan-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/ayam-pejantan-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'ayam-potong-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/ayam-potong-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'ayam-potong',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/ayam-potong.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'babat-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/babat-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'babat',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/babat.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'bawal-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/bawal-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'bawal',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/bawal.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'cumi-dua-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/cumi-dua-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'cumi-dua',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/cumi-dua.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'cumi-satu-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/cumi-satu-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'cumi-satu',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/cumi-satu.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'cumi-tiga-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/cumi-tiga-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'cumi-tiga',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/cumi-tiga.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-dua-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-dua-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-dua',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-dua.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-empat-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-empat-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-empat',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-empat.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-lima-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-lima-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-lima',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-lima.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-satu-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-satu-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-satu',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-satu.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-tiga-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-tiga-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'daging-sapi-tiga',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/daging-sapi-tiga.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'gurame-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/gurame-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'gurame',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/gurame.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'hati-sapi-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/hati-sapi-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'hati-sapi',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/hati-sapi.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'iga-dua-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/iga-dua-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'iga-dua',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/iga-dua.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'iga-empat-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/iga-empat-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'iga-empat',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/iga-empat.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'iga-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/iga-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'iga',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/iga.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'ikan-mas-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/ikan-mas-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'ikan-mas',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/ikan-mas.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'kakap-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/kakap-merah-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'kakap-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/kakap-merah.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'kembung-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/kembung-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'kembung',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/kembung.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'kulit-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/kulit-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'kulit',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/kulit.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'lele-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/lele-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'lele',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/lele.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'nila-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/nila-merah-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'nila-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/nila-merah.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'nila-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/nila-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'nila',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/nila.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'peda-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/peda-merah-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'peda-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/peda-merah.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'pindang-tongkol-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/pindang-tongkol-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'pindang-tongkol',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/pindang-tongkol.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'sarden-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/sarden-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'sarden',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/sarden.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'steak-dua-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/steak-dua-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'steak-dua',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/steak-dua.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'steak-empat-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/steak-empat-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'steak-empat',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/steak-empat.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'steak-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/steak-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'steak',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/steak.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'teri-putih-medan-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/teri-putih-medan-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'teri-putih-medan',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/teri-putih-medan.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'tongkol-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/tongkol-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'tongkol',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/tongkol.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'tuna-sliced-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/tuna-sliced-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'tuna-sliced',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/tuna-sliced.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'udang-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/udang-plain.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'udang',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/udang.jpg',
                'categories_id'=>3,
            ],
            [
                'name'=>'yoghurt2',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/daging/yoghurt2.jpg',
                'categories_id'=>4,
            ],
            [
                'name'=>'yoghurt3',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/yoghurt/yoghurt3.jpg',
                'categories_id'=>4,
            ],
            [
                'name'=>'yoghurt4',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/yoghurt/yoghurt4.jpg',
                'categories_id'=>4,
            ],
            [
                'name'=>'yoghurt',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/yoghurt/yoghurt.jpg',
                'categories_id'=>4,
            ],
            [
                'name'=>'blackmond-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/blackmond-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'blackmond',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/blackmond.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'blackthins-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/blackthins-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'blackthins',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/blackthins.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-basil-besar-kecil-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-basil-besar-kecil-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-basil-besar-kecil',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-basil-besar-kecil.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-basil-besar-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-basil-besar-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-basil-besar',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-basil-besar.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-basil-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-basil-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-basil',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-basil.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-bit-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-bit-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-bit',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-bit.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-kale-leave-kecil-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-kale-leave-kecil-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-kale-leave-kecil',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-kale-leave-kecil.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-kale-leaves-besar-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-kale-leaves-besar-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-kale-leaves-besar',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-kale-leaves-besar.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-kale-leaves-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-kale-leaves-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-kale-leaves',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-kale-leaves.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-red-spinach-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-red-spinach-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-red-spinach',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-red-spinach.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-tomat-besar-kecil-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-tomat-besar-kecil-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-tomat-besar-kecil',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-tomat-besar-kecil.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-tomat-besar-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-tomat-besar-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-tomat-besar',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-tomat-besar.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-tomat-kecil-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-tomat-kecil-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'mie-tomat-kecil',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/mie-tomat-kecil.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'pasta-bolognese-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/pasta-bolognese-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'pasta-bolognese',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/pasta-bolognese.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'pasta-fucini-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/pasta-fucini-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'pasta-fucini',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/pasta-fucini.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'pasta-macncheese-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/pasta-macncheese-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'pasta-macncheese',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/pasta-macncheese.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'tepung-bumbu-serbaguna-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/tepung-bumbu-serbaguna-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'tepung-bumbu-serbaguna',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/tepung-bumbu-serbaguna.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'tepung-mocaf-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/tepung-mocaf-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'tepung-mocaf',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/tepung-mocaf.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'tepung-pancake-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/tepung-pancake-plain.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'tepung-pancake',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/ladanglima/tepung-pancake.jpg',
                'categories_id'=>5,
            ],
            [
                'name'=>'gula-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/gulamerah/gula-merah-plain.jpg',
                'categories_id'=>6,
            ],
            [
                'name'=>'gula-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/gulamerah/gula-merah.jpg',
                'categories_id'=>6,
            ],
            [
                'name'=>'gula-merah-dua-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/gulamerah/gula-merah-dua-plain.jpg',
                'categories_id'=>6,
            ],
            [
                'name'=>'gula-merah-dua',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/gulamerah/gula-merah-dua.jpg',
                'categories_id'=>6,
            ],
            [
                'name'=>'jahe-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/jahe-plain.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'jahe',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/jahe.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'bawang-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/bawang-merah-plain.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'bawang-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/bawang-merah.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'bawang-putih-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/bawang-putih-plain.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'bawang-putih',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/bawang-putih.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'cabe-merah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/cabe-merah-plain.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'cabe-merah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/cabe-merah.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'kemiri-basah-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/kemiri-basah-plain.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'kemiri-basah',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/kemiri-basah.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'kemiri-kering-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/kemiri-kering-plain.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'kemiri-kering',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/kemiri-kering.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'kunyit-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/kunyit-plain.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'kunyit',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/kunyit.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'laos-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/laos-plain.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'laos',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/bumbugiling/laos.jpg',
                'categories_id'=>7,
            ],
            [
                'name'=>'oncom-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/olahankacangkedelai/oncom-plain.jpg',
                'categories_id'=>8,
            ],
            [
                'name'=>'oncom',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/olahankacangkedelai/oncom.jpg',
                'categories_id'=>8,
            ],
            [
                'name'=>'tahu-kuning-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/olahankacangkedelai/tahu-kuning-plain.jpg',
                'categories_id'=>8,
            ],
            [
                'name'=>'tahu-kuning',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/olahankacangkedelai/tahu-kuning.jpg',
                'categories_id'=>8,
            ],
            [
                'name'=>'tahu-putih-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/olahankacangkedelai/tahu-putih-plain.jpg',
                'categories_id'=>8,
            ],
            [
                'name'=>'tahu-putih',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/olahankacangkedelai/tahu-putih.jpg',
                'categories_id'=>8,
            ],
            [
                'name'=>'tempe-plain',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/olahankacangkedelai/tempe-plain.jpg',
                'categories_id'=>8,
            ],
            [
                'name'=>'tempe',
                'price'=>'1000',
                'unit' => 1,
            'stock' => 10,
                'image'=>'/public/image/olahankacangkedelai/tempe.jpg',
                'categories_id'=>8,
            ],
        ]);
    }
}
